apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvc-deployment
  labels:
    app: mvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mvc
  template:
    metadata:
      labels:
        app: mvc
    spec:
      containers:
      - name: mvc
        image: 12chizor3/products-store-mvc:1.0
        ports:
        - containerPort: 80
